USE SAKILA;
-- Fetch static value
SELECT 'AISHWARYA';
SELECT 'AISHWARYA' AS 'CR';
select 100+200 AS TOTAL;
select 100+200 AS 'TOTAL VALUE';
select 100+200 AS "TOTAL VALUE";

SELECT PI();
SELECT MOD(45,7);
SELECT SQRT(25);

-- FETCH RECORDS FROM TABLE
SELECT * FROM ACTOR;
SELECT * FROM SAKILA.ACTOR;

-- SORT ORDER
SELECT * FROM ACTOR
ORDER BY FIRST_NAME;
SELECT * FROM ACTOR
ORDER BY FIRST_NAME ASC;
SELECT * FROM ACTOR
ORDER BY FIRST_NAME DESC;
SELECT * FROM ACTOR
ORDER BY 1;
SELECT * FROM ACTOR
ORDER BY 2;
SELECT * FROM ACTOR
ORDER BY 2 DESC;

-- FILTERING
SELECT * FROM ACTOR
WHERE FIRST_NAME = 'WoODY';
SELECT * FROM ACTOR
WHERE FIRST_NAME = 'WoODY'
ORDER BY 3 DESC;

SELECT * FROM ACTOR
WHERE ACTOR_ID >195
ORDER BY ACTOR_ID;

SELECT FIRST_NAME, LAST_NAME FROM ACTOR
ORDER BY FIRST_NAME, LAST_NAME;

SELECT FIRST_NAME, LAST_NAME FROM ACTOR
ORDER BY FIRST_NAME ASC, LAST_NAME ASC;

SELECT FIRST_NAME, LAST_NAME FROM ACTOR
ORDER BY FIRST_NAME ASC, LAST_NAME DESC;

-- EMPTY RESULT SET
SELECT * FROM ACTOR
WHERE FALSE;

SELECT * FROM ACTOR
WHERE 1 = 2;

SELECT * FROM ACTOR
WHERE TRUE;



